"""Train Ultralytics detectors from the fold YAML files generated by main.py."""

import argparse
import json
from pathlib import Path
from typing import Iterable

from ultralytics import YOLO

from config.config_loader import ConfigLoader


def _fold_number(data: Path) -> int | None:
    try:
        return int(data.stem.removeprefix("fold_"))
    except ValueError:
        return None


def discover_folds(config_path: Path, mode: str) -> list[Path]:
    loader = ConfigLoader(config_path)
    matching = [p for p in loader.processes if p.slicing.slicing_mode == mode]
    if not matching:
        raise ValueError(f"No process configured for slicing mode '{mode}'.")
    output = Path(matching[0].dataset.output_path)
    folds = sorted(output.glob("fold_*.yaml"), key=lambda p: _fold_number(p) or 0)
    if not folds:
        raise FileNotFoundError(
            f"No fold YAML found in {output}. Run 'python main.py' first."
        )
    return folds


def train_fold(
    data: Path,
    initial_model: Path,
    models_root: Path,
    mode: str,
    epochs: int,
    imgsz: int,
    batch: int,
    device: str,
    workers: int,
    seed: int,
) -> Path:
    data = data.resolve()
    if not data.is_file():
        raise FileNotFoundError(f"Dataset YAML not found: {data}")
    if not initial_model.is_file():
        raise FileNotFoundError(f"Initial model not found: {initial_model}")

    fold = _fold_number(data)
    fold_name = f"fold_{fold}" if fold is not None else data.stem
    project = (models_root / mode / fold_name / "yolo").resolve()

    model = YOLO(str(initial_model.resolve()))
    result = model.train(
        data=str(data),
        epochs=epochs,
        imgsz=imgsz,
        batch=batch,
        device=device,
        workers=workers,
        seed=seed,
        project=str(project),
        name="train",
        exist_ok=True,
    )

    result_save_dir = getattr(result, "save_dir", None)
    trainer_save_dir = getattr(getattr(model, "trainer", None), "save_dir", None)
    save_dir_value = result_save_dir or trainer_save_dir
    if save_dir_value is None:
        raise RuntimeError("Ultralytics did not report the training output directory")
    save_dir = Path(save_dir_value)
    checkpoint = save_dir / "weights" / "best.pt"
    if not checkpoint.is_file():
        raise RuntimeError(f"Training finished without best.pt in {save_dir}")

    manifest = {
        "mode": mode,
        "fold": fold,
        "architecture": "yolo",
        "dataset": str(data),
        "initial_model": str(initial_model.resolve()),
        "checkpoint": str(checkpoint.resolve()),
        "training": {
            "epochs": epochs,
            "imgsz": imgsz,
            "batch": batch,
            "device": device,
            "workers": workers,
            "seed": seed,
        },
    }
    manifest_path = project / "manifest.json"
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    return checkpoint


def train_many(datasets: Iterable[Path], args: argparse.Namespace) -> list[Path]:
    return [
        train_fold(
            data=data,
            initial_model=args.model,
            models_root=args.models_root,
            mode=args.mode,
            epochs=args.epochs,
            imgsz=args.imgsz,
            batch=args.batch,
            device=args.device,
            workers=args.workers,
            seed=args.seed,
        )
        for data in datasets
    ]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train YOLO using datasets generated by the slicing pipeline."
    )
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--data", type=Path, help="Path to one fold_N.yaml")
    source.add_argument(
        "--all-folds", action="store_true", help="Train every fold for --mode"
    )
    parser.add_argument("--mode", choices=("sahi", "asahi"), required=True)
    parser.add_argument(
        "--model", type=Path, default=Path(__file__).with_name("yolo26n.pt")
    )
    parser.add_argument("--models-root", type=Path)
    parser.add_argument("--config", type=Path, default=Path("config.yaml"))
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--imgsz", type=int, default=640)
    parser.add_argument("--batch", type=int, default=16)
    parser.add_argument("--device", default="cpu")
    parser.add_argument("--workers", type=int, default=4)
    parser.add_argument("--seed", type=int, default=42)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.models_root is None:
        args.models_root = Path(ConfigLoader(args.config).paths.models)
    datasets = (
        discover_folds(args.config, args.mode)
        if args.all_folds
        else [args.data]
    )
    checkpoints = train_many(datasets, args)
    for checkpoint in checkpoints:
        print(checkpoint)


if __name__ == "__main__":
    main()
